version: '3'
services:
  app:
    env_file:
        - ./.env
    build:
      context: ./
    volumes:
      - ./webtools-redcap-ldap:/var/www/html/webtools/redcap-ldap/:delegated
    ports:
      - "80:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    #network_mode: host
volumes:
  logs-volume: